temp: hello
jmsPort: 1234

logging:
  level: INFO
  loggers:
    com.richo.casinobots.web: INFO
    io.dropwizard: INFO
  appenders:
    - type: console

server:
  rootPath: '/api/*'
  applicationConnectors:
  - type: http
    port: 80
  adminConnectors:
  - type: http
    port: 81