offlineMode: false

logging:
  level: INFO
  loggers:
    com.richo.reader: ALL
    io.dropwizard: INFO
  appenders:
    - type: console

server:
  rootPath: '/api/*'
  applicationConnectors:
  - type: http
    port: 80
  adminConnectors:
  - type: http
    port: 81
  requestLog:
    appenders: []