version: "3"
services:
  frontend:
    image: richodemus/autoplaylist-frontend:latest
    ports:
      - "3000:5000"

  backend:
    image: richodemus/autoplaylist-backend:latest
    ports:
      - "8080:8080"
    environment:
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - REDIRECT_URL=${REDIRECT_URL}
