version: '2'
services:
  reader:
    image: richodemus/reader:latest
    volumes:
      - "./data:/reader/data"
    ports:
      - "8080:8080"
      - "8081:8081"
  chronicler:
    image: richodemus/chronicler:latest
    ports:
      - "8090:8080"
    volumes:
      - "./data/events:/chronicler/data"
