version: 2.0
workflows:
  version: 2
  build:
    jobs:
      - build
      - push:
          requires:
            - build
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - push
          filters:
            branches:
              only: master

jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - run: mkdir -p /workspace
      - checkout
      - setup_remote_docker
      - run:
          name: Build docker images
          command: ./build.sh
          no_output_timeout: 30m
      - run:
          name: Write frontend image to disk
          command: docker save --output /workspace/frontend.img richodemus/autoplaylist-frontend:latest
          no_output_timeout: 30m
      - run:
          name: Write backend image to disk
          command: docker save --output /workspace/backend.img richodemus/autoplaylist-backend:latest
          no_output_timeout: 30m
      - persist_to_workspace:
          root: /workspace
          paths:
            - frontend.img
            - backend.img
    
  push:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: /workspace
      - run:
          name: Read frontend image from disk
          command: docker load --input /workspace/frontend.img
          no_output_timeout: 30m
      - run:
          name: Read backend image from disk
          command: docker load --input /workspace/backend.img
          no_output_timeout: 30m
      - run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push richodemus/autoplaylist-frontend:latest
          docker push richodemus/autoplaylist-backend:latest

  deploy:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "00:aa:c3:0b:30:bd:7c:6e:18:03:6d:7b:a4:84:b7:45"
      - run: |
          echo $KNOWN_HOST >> ~/.ssh/known_hosts
          ssh richodemus@richodemus.com << EOF
            docker pull richodemus/autoplaylist-frontend:latest
            docker pull richodemus/autoplaylist-backend:latest

            docker rm -f autoplaylist-frontend
            docker rm -f autoplaylist-backend

            docker run --name autoplaylist-frontend -d --log-driver=gcplogs --log-driver=json-file richodemus/autoplaylist-frontend:latest
            docker run --name autoplaylist-backend -d --log-driver=gcplogs --log-driver=json-file \
              -p 9090:8080 \
              -e CLIENT_ID=df0732a2defe44ecabd30868fa57a2d5 \
              -e CLIENT_SECRET=$SPOTIFY_SECRET \
              -e REDIRECT_URL=https://autoplaylist.richodemus.com/callback \
              -e GCS_PROJECT=richo-main \
              -e GCS_BUCKET=richo-autoplaylist \
              richodemus/autoplaylist-backend:latest

            docker system prune -f
          EOF
