server:
  servlet:
    session:
      cookie:
        max-age: 90d
#        secure: true # use a special production profile with this flag
management:
  endpoints:
    web:
      exposure:
        include:
          - "info"
          - "health"
          - "metrics"

spotify:
  url: "https://api.spotify.com"
  accountsUrl: "https://accounts.spotify.com"
  clientId: "your-id"
  clientSecret: "your-secret"
  redirectUrl: "your-redirect-url"
