export const LOGIN_VIEW = "LOGIN_VIEW";
export const WELCOME_VIEW = "WELCOME_VIEW";
export const LIST_PLAYLISTS_VIEW = "LIST_PLAYLISTS_VIEW";
export const EDIT_PLAYLIST_VIEW = "EDIT_PLAYLIST_VIEW";
export const ARTIST_SEARCH_VIEW = "ARTIST_SEARCH_VIEW";
export const LOADING_VIEW = "LOADING_VIEW";
