saveRoot: data

logging:
  level: INFO
  loggers:
    com.richo.reader: INFO
    io.dropwizard: INFO
  appenders:
    - type: console

server:
  rootPath: '/api/*'
  applicationConnectors:
  - type: http
    port: 8080
  adminConnectors:
  - type: http
    port: 8081
  requestLog:
    appenders: []
