version: '2'
services:
  reader:
    build: .
    volumes:
      - "./data:/reader/data"
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      GCP_PROJECT: richo-main
      GCP_BUCKET: richo-reader
      GOOGLE_APPLICATION_CREDENTIALS: /google-service-key.json
