server:
  servlet:
    session:
      cookie:
        max-age: 90d
#        secure: true # use a special production profile with this flag
management:
  endpoints:
    web:
      exposure:
        include:
          - "info"
          - "health"
          - "metrics"

#gcs:
#  project: "gcs-project"
#  bucket: "gcs-bucket"

saveRoot: data
inviteCode:

gcp:
  project: "project"
  bucket: "bucket"
  apiKey: "yt-api-key"
